<?php

/*
|--------------------------------------------------------------------------
| Announcements
|--------------------------------------------------------------------------
|
| ─────────────────────────────────────────────────────────────────────────
| ANNOUNCEMENTS ARE NOT NOTIFICATIONS
|
| Decided 2026-08-28. Two surfaces, one shared feed component:
|
|   THE BOARD (/announcements)  written by a person, broadcast to everyone,
|                               scheduled, expires. Plus milestones — birthdays
|                               and work anniversaries — which are generated but
|                               are still things the whole company reads.
|
|   THE BELL (/notifications)   generated by an event, addressed to ONE person,
|                               usually actionable, cleared when read.
|
| Merging them makes both worse. Task and ticket events are high-volume and
| nobody else's business; put them on the board and the day somebody posts
| "office closed Friday" it sits under forty task assignments and people turn
| up. The board is only worth having while it stays readable.
| ─────────────────────────────────────────────────────────────────────────
|
| Categories moved to master data (§12) on 2026-09-21 — see
| MasterDataItem::ANNOUNCEMENT_CATEGORIES and
| App\Support\AnnouncementPresenter::categories(), which is now the only
| reader. Their labels live in the Admin Panel; their tone and icon stay in
| AnnouncementPresenter::CATEGORY_STYLES, because MasterDataItem carries no
| such columns and a category must not borrow a feedback colour (§7).
|
*/

return [

    /*
    | Who may post (decided 2026-08-28): HR, project managers and the owner.
    | Broad enough that announcements actually get made, narrow enough that the
    | board keeps its weight. The permission name the RBAC engine will use.
    */
    'post_permission' => 'announcements.post',

    /*
    | ─────────────────────────────────────────────────────────────────────────
    | DECLARING A CLOSURE IS NOT THE SAME ACT AS POSTING
    |
    | Decided 2026-09-03, when Attendance started reading holidays from this
    | board (App\Support\Holidays).
    |
    | A holiday announcement carries `observed` dates, and those dates close the
    | office: nobody is marked absent on them. That makes setting them a WRITE
    | TO THE ATTENDANCE RECORD, performed through the announcements form.
    |
    | `announcements.post` is deliberately broad — HR, project managers and the
    | owner — because a board nobody can post to is a board nobody reads. That
    | breadth is right for notices and wrong for closures: a project manager
    | announcing a team event should not hold the key that rewrites everyone's
    | attendance for a day.
    |
    | So the closure dates are their own permission: HR and the owner. The
    | announcement is still theirs to write; the closure is not theirs to
    | declare.
    | ─────────────────────────────────────────────────────────────────────────
    */
    'holiday_permission' => 'announcements.holiday',

    /*
    | Milestones post themselves on the day, and anyone may opt out of their own
    | (decided 2026-08-28). Not everyone wants their birthday on a company
    | board, and finding out you cannot turn it off is a bad way to learn it.
    |
    | `window_days` is how far ahead the board looks, so "coming up this week"
    | is possible without anybody maintaining a list.
    */
    'milestones' => [
        'window_days' => 14,
        'birthdays' => true,
        'anniversaries' => true,
    ],

];
