<?php

/*
|--------------------------------------------------------------------------
| Announcements
|--------------------------------------------------------------------------
|
| ─────────────────────────────────────────────────────────────────────────
| ANNOUNCEMENTS ARE NOT NOTIFICATIONS
|
| Decided 2026-08-28. Two surfaces, one shared feed component:
|
|   THE BOARD (/announcements)  written by a person, broadcast to everyone,
|                               scheduled, expires. Plus milestones — birthdays
|                               and work anniversaries — which are generated but
|                               are still things the whole company reads.
|
|   THE BELL (/notifications)   generated by an event, addressed to ONE person,
|                               usually actionable, cleared when read.
|
| Merging them makes both worse. Task and ticket events are high-volume and
| nobody else's business; put them on the board and the day somebody posts
| "office closed Friday" it sits under forty task assignments and people turn
| up. The board is only worth having while it stays readable.
| ─────────────────────────────────────────────────────────────────────────
|
| Categories are master data and move to the Admin Panel (§12) with the rest of
| company configuration. `tone` maps to the chip colours in
| resources/css/pages/announcements.css — categorical accents, never feedback
| colours (§7): a category must not borrow the green that means "active" or the
| red that means "expired".
|
*/

return [

    'categories' => [
        'policy' => ['label' => 'Policy', 'tone' => 'an-policy', 'icon' => 'reports'],
        'hr' => ['label' => 'HR', 'tone' => 'an-hr', 'icon' => 'employees'],
        'holiday' => ['label' => 'Holiday', 'tone' => 'an-holiday', 'icon' => 'calendar'],
        'event' => ['label' => 'Event', 'tone' => 'an-event', 'icon' => 'meetings'],
        'training' => ['label' => 'Training', 'tone' => 'an-training', 'icon' => 'tasks'],
        'it' => ['label' => 'IT', 'tone' => 'an-it', 'icon' => 'settings'],

        /*
        | Milestones are generated, not written. They are a category rather than
        | a separate feed because everybody reads them the same way — but they
        | can never be authored by hand, and AnnouncementPresenter::isAuthorable()
        | is what keeps this one out of the compose form.
        */
        'milestone' => ['label' => 'Milestone', 'tone' => 'an-milestone', 'icon' => 'announcements'],
    ],

    /*
    | Who may post (decided 2026-08-28): HR, project managers and the owner.
    | Broad enough that announcements actually get made, narrow enough that the
    | board keeps its weight. The permission name the RBAC engine will use.
    */
    'post_permission' => 'announcements.post',

    /*
    | Milestones post themselves on the day, and anyone may opt out of their own
    | (decided 2026-08-28). Not everyone wants their birthday on a company
    | board, and finding out you cannot turn it off is a bad way to learn it.
    |
    | `window_days` is how far ahead the board looks, so "coming up this week"
    | is possible without anybody maintaining a list.
    */
    'milestones' => [
        'window_days' => 14,
        'birthdays' => true,
        'anniversaries' => true,
    ],

];
