<?php

namespace App\Http\Controllers;

use App\Support\AnnouncementPresenter;
use App\Support\Demo\DemoAnnouncements;
use App\Support\Demo\DemoEmployees;
use App\Support\Milestones;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Routing\Controller;
use Illuminate\Support\Collection;
use Illuminate\Validation\Rule;

/**
 * Announcements — the board everybody reads.
 *
 * Three pages: the board (`/announcements`), the managing list
 * (`/announcements/manage`) and the compose form (`/announcements/compose`).
 * One announcement lives at `/announcements/{announcement}`.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * THIS IS NOT THE NOTIFICATION FEED
 *
 * Decided 2026-08-28. An announcement is written by a person, broadcast, and
 * expires. A notification is generated by an event, addressed to one person,
 * and cleared when read — see App\Http\Controllers\NotificationController.
 *
 * Task and ticket events do NOT come here. They are high-volume and nobody
 * else's business, and a board they flood is a board nobody reads — which is
 * exactly when "office closed Friday" gets missed.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHAT THE BACKEND OWES
 *
 * 1. `announcements.post` IS ITS OWN PERMISSION — HR, project managers and the
 *    owner (decided 2026-08-28). Everyone else reads.
 *
 * 2. MILESTONES ARE COMPUTED, NEVER STORED. Birthdays and work anniversaries
 *    come from employee records on every request. A stored milestone post would
 *    be wrong the following year and would survive somebody opting out.
 *
 * 3. A BIRTHDAY IS A DAY AND A MONTH. Date of birth is stored in full and the
 *    year never reaches a page — see App\Support\Milestones.
 *
 * 4. AUDIENCE IS ENFORCED IN THE QUERY. A "managers only" announcement must not
 *    be fetched for somebody who is not one; filtering it out in the view means
 *    it was in the response.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * A HOLIDAY ANNOUNCEMENT WRITES TO THE ATTENDANCE RECORD
 *
 * Added 2026-09-03. A holiday post carries `observed_from`/`observed_to` — the
 * days the office is SHUT, which is not the window the notice is up for — and
 * App\Support\Holidays reads them so nobody is marked absent on those days.
 *
 * That is the right design: one list cannot disagree with itself, and the
 * alternative is a holiday calendar in the Admin Panel that goes stale against
 * the notices people actually read. But it means this form is an attendance
 * write, and three things follow from that:
 *
 * 5. `announcements.holiday` IS ITS OWN PERMISSION, separate from
 *    `announcements.post`. Posting is broad — HR, project managers, the owner —
 *    because a board nobody can post to is a board nobody reads. Closing the
 *    office is HR and the owner. See config/announcements.php.
 *
 * 6. CHANGING OR REMOVING OBSERVED DATES ON A PAST HOLIDAY IS AUDITED (§6). It
 *    retroactively changes whether people were absent, which is exactly the
 *    class of edit that has to leave a trace naming who and when.
 *
 * 7. THE FORM SHOWS THE CONSEQUENCE, AND THE WEEKDAY. "4 Sep" reads fine when
 *    you meant the 14th; "Friday 4 September, the office will be closed" is
 *    where somebody notices. The damage from a wrong date is contained — it can
 *    only hide absences, never alter a recorded time — and the attendance roll
 *    catches it the same day (AttendancePresenter::holidayLooksWrong), but the
 *    cheapest place to stop it is before it is posted.
 * ─────────────────────────────────────────────────────────────────────────────
 */
class AnnouncementController extends Controller
{
    protected const PER_PAGE = 10;

    /**
     * GET /announcements — the board.
     */
    public function index(Request $request): Response
    {
        $category = $request->validate([
            'category' => ['nullable', Rule::in(array_keys(AnnouncementPresenter::categories()))],
        ])['category'] ?? null;

        $board = DemoAnnouncements::board();

        return response()->view('announcements.index', [
            'activeNav' => 'announcements',
            'announcements' => $category ? $board->where('category', $category)->values() : $board,
            'category' => $category,
            'categories' => DemoAnnouncements::categoryCounts(),
            'boardTotal' => $board->count(),
            // Coming up, so the board is useful before the day rather than only
            // on it.
            'upcoming' => Milestones::upcoming(),
            // TODO (backend phase): `announcements.post`.
            'canPost' => true,
        ]);
    }

    /**
     * GET /announcements/manage — everything, including drafts and expired.
     */
    public function manage(Request $request): Response
    {
        $tab = $request->validate([
            'tab' => ['nullable', Rule::in(array_merge(['all'], AnnouncementPresenter::statusOptions()))],
        ])['tab'] ?? 'all';

        $all = DemoAnnouncements::authored();
        $shown = $tab === 'all' ? $all : $all->where('status', $tab)->values();

        $filters = $this->filters($request);
        $counts = DemoAnnouncements::stats($all);

        return response()->view('announcements.manage', [
            'activeNav' => 'announcements',
            // Only authored posts. A computed milestone has nothing to edit,
            // schedule or delete, so listing it here would offer actions that
            // cannot work.
            'announcements' => $this->paginate($this->matching($shown, $filters), $request),
            'stats' => $counts,
            'tab' => $tab,
            'tabCounts' => [
                'all' => $counts['total'],
                'active' => $counts['active'],
                'scheduled' => $counts['scheduled'],
                'draft' => $counts['draft'],
                'expired' => $counts['expired'],
            ],
            'canPost' => true,
        ] + $filters);
    }

    /**
     * GET /announcements/compose
     */
    public function create(): Response
    {
        return response()->view('announcements.compose', [
            'activeNav' => 'announcements',
            // Milestones are excluded: a hand-written one would sit in the feed
            // looking identical to a computed one and be wrong next year.
            'categories' => AnnouncementPresenter::authorableCategories(),
            'audiences' => AnnouncementPresenter::audiences(),
            'departments' => DemoEmployees::all()->pluck('department')->unique()->sort()->values()->all(),
            // Closure dates are a write to the attendance record made through
            // this form, so they are their own permission — HR and the owner,
            // not everyone who may post.
            // TODO (backend phase): gate on `announcements.holiday` (§2.6).
            'canDeclareHoliday' => true,
        ]);
    }

    /**
     * GET /announcements/{announcement}
     */
    public function show(string $announcement): Response
    {
        $record = DemoAnnouncements::find($announcement);

        abort_if($record === null, 404);

        return response()->view('announcements.show', [
            'activeNav' => 'announcements',
            'announcement' => $record,
            'canPost' => true,
        ]);
    }

    /**
     * @return array<string, mixed>
     */
    protected function filters(Request $request): array
    {
        $validated = $request->validate([
            'q' => ['nullable', 'string', 'max:100'],
            'category' => ['nullable', Rule::in(array_keys(AnnouncementPresenter::categories()))],
        ]);

        $search = trim($validated['q'] ?? '');

        return [
            'search' => $search,
            'filterCategory' => $validated['category'] ?? null,
            'filtered' => $search !== '' || ($validated['category'] ?? null) !== null,
        ];
    }

    /**
     * @param  Collection<int, array<string, mixed>>  $announcements
     * @param  array<string, mixed>  $filters
     * @return Collection<int, array<string, mixed>>
     */
    protected function matching(Collection $announcements, array $filters): Collection
    {
        return $announcements
            ->when($filters['search'] !== '', fn (Collection $rows) => $rows->filter(
                fn (array $a) => str_contains(
                    mb_strtolower($a['title'].' '.$a['id'].' '.$a['body']),
                    mb_strtolower($filters['search'])
                )
            ))
            ->when($filters['filterCategory'], fn (Collection $rows) => $rows->where('category', $filters['filterCategory']))
            ->sortByDesc('published_at')
            ->values();
    }

    /**
     * @param  Collection<int, array<string, mixed>>  $rows
     * @return LengthAwarePaginator<int, array<string, mixed>>
     */
    protected function paginate(Collection $rows, Request $request): LengthAwarePaginator
    {
        $page = LengthAwarePaginator::resolveCurrentPage();

        return new LengthAwarePaginator(
            items: $rows->forPage($page, self::PER_PAGE)->values(),
            total: $rows->count(),
            perPage: self::PER_PAGE,
            currentPage: $page,
            options: ['path' => $request->url(), 'query' => $request->query()],
        );
    }
}
