<?php

namespace App\Http\Controllers;

use App\Models\Announcement;
use App\Models\Employee;
use App\Models\MasterDataItem;
use App\Support\AnnouncementDirectory;
use App\Support\AnnouncementPresenter;
use App\Support\Audit\AuditLog;
use App\Support\Milestones;
use App\Support\Rbac\Rbac;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Routing\Controller;
use Illuminate\Support\Collection;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;

/**
 * Announcements — the board everybody reads.
 *
 * Three pages: the board (`/announcements`), the managing list
 * (`/announcements/manage`) and the compose form (`/announcements/compose`).
 * One announcement lives at `/announcements/{announcement}`.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * THIS IS NOT THE NOTIFICATION FEED
 *
 * Decided 2026-08-28. An announcement is written by a person, broadcast, and
 * expires. A notification is generated by an event, addressed to one person,
 * and cleared when read — see App\Http\Controllers\NotificationController.
 *
 * Task and ticket events do NOT come here. They are high-volume and nobody
 * else's business, and a board they flood is a board nobody reads — which is
 * exactly when "office closed Friday" gets missed.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHAT THE BACKEND OWES
 *
 * 1. `announcements.post` IS ITS OWN PERMISSION — HR, project managers and the
 *    owner (decided 2026-08-28). Everyone else reads.
 *
 * 2. MILESTONES ARE COMPUTED, NEVER STORED. Birthdays and work anniversaries
 *    come from employee records on every request. A stored milestone post would
 *    be wrong the following year and would survive somebody opting out.
 *
 * 3. A BIRTHDAY IS A DAY AND A MONTH. Date of birth is stored in full and the
 *    year never reaches a page — see App\Support\Milestones.
 *
 * 4. AUDIENCE IS ENFORCED IN THE QUERY. A "managers only" announcement must not
 *    be fetched for somebody who is not one; filtering it out in the view means
 *    it was in the response.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * A HOLIDAY ANNOUNCEMENT WRITES TO THE ATTENDANCE RECORD
 *
 * Added 2026-09-03. A holiday post carries `observed_from`/`observed_to` — the
 * days the office is SHUT, which is not the window the notice is up for — and
 * App\Support\Holidays reads them so nobody is marked absent on those days.
 *
 * That is the right design: one list cannot disagree with itself, and the
 * alternative is a holiday calendar in the Admin Panel that goes stale against
 * the notices people actually read. But it means this form is an attendance
 * write, and three things follow from that:
 *
 * 5. `announcements.holiday` IS ITS OWN PERMISSION, separate from
 *    `announcements.post`. Posting is broad — HR, project managers, the owner —
 *    because a board nobody can post to is a board nobody reads. Closing the
 *    office is HR and the owner. See config/announcements.php.
 *
 * 6. CHANGING OR REMOVING OBSERVED DATES ON A PAST HOLIDAY IS AUDITED (§6). It
 *    retroactively changes whether people were absent, which is exactly the
 *    class of edit that has to leave a trace naming who and when.
 *
 * 7. THE FORM SHOWS THE CONSEQUENCE, AND THE WEEKDAY. "4 Sep" reads fine when
 *    you meant the 14th; "Friday 4 September, the office will be closed" is
 *    where somebody notices. The damage from a wrong date is contained — it can
 *    only hide absences, never alter a recorded time — and the attendance roll
 *    catches it the same day (AttendancePresenter::holidayLooksWrong), but the
 *    cheapest place to stop it is before it is posted.
 * ─────────────────────────────────────────────────────────────────────────────
 */
class AnnouncementController extends Controller
{
    protected const PER_PAGE = 10;

    public function __construct(protected Rbac $rbac, protected AuditLog $audit)
    {
    }

    /**
     * GET /announcements — the board.
     */
    public function index(Request $request): Response
    {
        $category = $request->validate([
            'category' => ['nullable', Rule::in(array_keys(AnnouncementPresenter::categories()))],
        ])['category'] ?? null;

        $board = AnnouncementDirectory::board();

        return response()->view('announcements.index', [
            'activeNav' => 'announcements',
            'announcements' => $category ? $board->where('category', $category)->values() : $board,
            'category' => $category,
            'categories' => AnnouncementDirectory::categoryCounts(),
            'boardTotal' => $board->count(),
            // Coming up, so the board is useful before the day rather than only
            // on it.
            'upcoming' => Milestones::upcoming(),
            'canPost' => $this->rbac->can($request->user(), config('announcements.post_permission')),
        ]);
    }

    /**
     * GET /announcements/manage — everything, including drafts and expired.
     */
    public function manage(Request $request): Response
    {
        $tab = $request->validate([
            'tab' => ['nullable', Rule::in(array_merge(['all'], AnnouncementPresenter::statusOptions()))],
        ])['tab'] ?? 'all';

        $all = AnnouncementDirectory::authored();
        $shown = $tab === 'all' ? $all : $all->where('status', $tab)->values();

        $filters = $this->filters($request);
        $counts = AnnouncementDirectory::stats($all);

        return response()->view('announcements.manage', [
            'activeNav' => 'announcements',
            // Only authored posts. A computed milestone has nothing to edit,
            // schedule or delete, so listing it here would offer actions that
            // cannot work.
            'announcements' => $this->paginate($this->matching($shown, $filters), $request),
            'stats' => $counts,
            'tab' => $tab,
            'tabCounts' => [
                'all' => $counts['total'],
                'active' => $counts['active'],
                'scheduled' => $counts['scheduled'],
                'draft' => $counts['draft'],
                'expired' => $counts['expired'],
            ],
            'canPost' => $this->rbac->can($request->user(), config('announcements.post_permission')),
        ] + $filters);
    }

    /**
     * GET /announcements/compose
     */
    public function create(Request $request): Response
    {
        return response()->view('announcements.compose', [
            'activeNav' => 'announcements',
            'announcement' => null,
            'reference' => AnnouncementDirectory::nextReference(),
            // Milestones are excluded: a hand-written one would sit in the feed
            // looking identical to a computed one and be wrong next year.
            'categories' => AnnouncementPresenter::authorableCategories(),
            'audiences' => AnnouncementPresenter::audiences(),
            'departments' => MasterDataItem::inList(MasterDataItem::DEPARTMENTS)->active()->get(),
            /*
             * Closure dates are a write to the attendance record made through
             * this form, so they are their own permission — HR and the owner,
             * not everyone who may post (§2.6).
             */
            'canDeclareHoliday' => $this->rbac->can(
                $request->user(),
                AnnouncementPresenter::holidayPermission(),
            ),
        ]);
    }

    /* ══════════════════════════════════════════════════════════════════════
       THE WRITES
       ══════════════════════════════════════════════════════════════════════ */

    /**
     * Post to the board — as a draft, or published straight away.
     *
     * ─────────────────────────────────────────────────────────────────────────
     * THE CLOSURE DATES ARE DROPPED FROM ANYBODY WITHOUT THE PERMISSION
     *
     * Not refused — dropped, and the post still saves. Somebody who may post
     * but may not close the office writes their notice and it goes up; what
     * does not happen is the attendance record changing underneath it. Refusing
     * the whole post would lose what they wrote over a field they did not know
     * they could not use.
     * ─────────────────────────────────────────────────────────────────────────
     */
    public function store(Request $request): RedirectResponse
    {
        $author = $this->employeeFor($request);

        abort_if($author === null, 403);

        $data = $this->validated($request);

        $mayCloseTheOffice = $this->rbac->can($request->user(), AnnouncementPresenter::holidayPermission());

        $announcement = Announcement::create([
            'reference' => AnnouncementDirectory::nextReference(),
            'title' => $data['title'],
            'body' => $data['body'],
            'category' => $data['category'],
            'author_id' => $author->id,
            'audience' => $data['audience'],
            'audience_department_id' => $data['audience'] === 'everyone'
                ? null
                : ($data['audience_department_id'] ?? null),
            'for_clients' => $data['for_clients'] ?? false,
            'starts_on' => $data['starts_on'],
            'ends_on' => $data['ends_on'] ?? null,
            'observed_from' => $mayCloseTheOffice ? ($data['observed_from'] ?? null) : null,
            'observed_to' => $mayCloseTheOffice
                ? ($data['observed_to'] ?? $data['observed_from'] ?? null)
                : null,
            // Published now, or left as a draft for somebody to publish.
            'published_at' => ($data['publish'] ?? false) ? now() : null,
            'pinned' => $data['pinned'] ?? false,
        ]);

        $this->audit->record(
            action: $announcement->isDraft() ? AuditLog::ANNOUNCEMENT_DRAFTED : AuditLog::ANNOUNCEMENT_POSTED,
            actor: $request->user(),
            entityType: 'announcement',
            entityId: $announcement->reference,
            after: $this->describe($announcement),
            request: $request,
        );

        return redirect()
            ->route('announcements.show', ['announcement' => $announcement->reference])
            ->with('status', $announcement->isDraft()
                ? 'Saved as a draft. Nothing is on the board yet.'
                : 'Posted to the board.')
            ->with('status_tone', 'success');
    }

    /**
     * Publish a draft.
     *
     * Its own act, because publishing a holiday notice is what closes the
     * office — a draft closes nothing, and the moment it goes up is the moment
     * attendance changes.
     */
    public function publish(Request $request, string $announcement): RedirectResponse
    {
        $record = $this->find($announcement);
        $model = $record['model'];

        if ($model->published_at !== null) {
            return redirect()
                ->route('announcements.show', ['announcement' => $model->reference])
                ->with('status', 'This was already published.')
                ->with('status_tone', 'info');
        }

        if ($model->observed_from !== null
            && ! $this->rbac->can($request->user(), AnnouncementPresenter::holidayPermission())) {
            /*
             * A draft that closes the office may only be published by somebody
             * who could have written those dates in the first place. Otherwise
             * the permission is a formality anybody can route around by asking
             * a colleague to press the button.
             */
            abort(403);
        }

        $model->update(['published_at' => now()]);

        $this->audit->record(
            action: AuditLog::ANNOUNCEMENT_POSTED,
            actor: $request->user(),
            entityType: 'announcement',
            entityId: $model->reference,
            before: 'draft',
            after: $this->describe($model),
            request: $request,
        );

        return redirect()
            ->route('announcements.show', ['announcement' => $model->reference])
            ->with('status', 'Posted to the board.')
            ->with('status_tone', 'success');
    }

    /**
     * Take it down early.
     *
     * ─────────────────────────────────────────────────────────────────────────
     * EXPIRING A HOLIDAY NOTICE DOES NOT REOPEN THE OFFICE
     *
     * The observed dates stay. The office was shut on those days whatever the
     * board says about it now, and clearing them would retroactively mark
     * everybody absent for a day the company closed — see App\Support\Holidays,
     * which reads published notices rather than live ones for exactly this
     * reason.
     * ─────────────────────────────────────────────────────────────────────────
     */
    public function expire(Request $request, string $announcement): RedirectResponse
    {
        $record = $this->find($announcement);
        $model = $record['model'];

        $model->update(['ends_on' => now()->subDay()->toDateString()]);

        $this->audit->record(
            action: AuditLog::ANNOUNCEMENT_EXPIRED,
            actor: $request->user(),
            entityType: 'announcement',
            entityId: $model->reference,
            after: 'Taken off the board'
                .($model->observed_from !== null ? ' — the closure dates are unchanged' : ''),
            request: $request,
        );

        return redirect()
            ->route('announcements.show', ['announcement' => $model->reference])
            ->with('status', $model->observed_from !== null
                ? 'Taken off the board. The days the office was closed are unchanged.'
                : 'Taken off the board.')
            ->with('status_tone', 'info');
    }

    /**
     * GET /announcements/{announcement}
     */
    public function show(Request $request, string $announcement): Response
    {
        $record = $this->find($announcement);

        return response()->view('announcements.show', [
            'activeNav' => 'announcements',
            'announcement' => $record,
            'canPost' => $this->rbac->can($request->user(), config('announcements.post_permission')),
        ]);
    }

    /**
     * @return array<string, mixed>
     */
    protected function find(string $reference): array
    {
        $found = AnnouncementDirectory::find($reference);

        abort_if($found === null, 404);

        return $found;
    }

    protected function employeeFor(Request $request): ?Employee
    {
        return Employee::where('user_id', $request->user()?->id)->first();
    }

    /**
     * @return array<string, mixed>
     */
    protected function validated(Request $request): array
    {
        $data = $request->validate([
            'title' => ['required', 'string', 'max:200'],
            'body' => ['required', 'string', 'max:5000'],
            'category' => ['required', Rule::in(array_keys(AnnouncementPresenter::authorableCategories()))],
            'audience' => ['required', Rule::in(array_keys(AnnouncementPresenter::audiences()))],
            'audience_department_id' => [
                'nullable',
                'required_unless:audience,everyone',
                Rule::exists('master_data_items', 'id')
                    ->where('list', MasterDataItem::DEPARTMENTS)
                    ->where('is_active', true),
            ],
            'starts_on' => ['required', 'date'],
            // The notice window. Nullable means it never comes down on its own.
            'ends_on' => ['nullable', 'date', 'after_or_equal:starts_on'],
            /*
             * The days the office is SHUT — a different range from the two
             * above, and the reason this form is an attendance write. Bounded
             * to a fortnight because a closure longer than that is not a
             * holiday notice, it is a typo somebody would otherwise discover in
             * next month's attendance report.
             */
            'observed_from' => ['nullable', 'date', 'required_with:observed_to'],
            'observed_to' => ['nullable', 'date', 'after_or_equal:observed_from'],
            'publish' => ['nullable', 'boolean'],
            'pinned' => ['nullable', 'boolean'],
            'for_clients' => ['nullable', 'boolean'],
        ]);

        if (($data['observed_from'] ?? null) !== null) {
            $from = \Illuminate\Support\Carbon::parse($data['observed_from']);
            $to = \Illuminate\Support\Carbon::parse($data['observed_to'] ?? $data['observed_from']);

            if ($from->diffInDays($to) > 14) {
                /*
                 * Checked here rather than as a rule, because `before_or_equal`
                 * compares against a field or a fixed date and not against
                 * "another field plus a fortnight" — written as a rule it
                 * silently never matched, which is worse than not having it.
                 */
                throw ValidationException::withMessages([
                    'observed_to' => 'A closure longer than a fortnight is almost always a mistyped date. Post two notices if it really is that long.',
                ]);
            }
        }

        return $data;
    }

    protected function describe(Announcement $announcement): string
    {
        return implode(' · ', array_filter([
            $announcement->title,
            $announcement->category,
            $announcement->audience === 'everyone'
                ? 'everyone'
                : (string) $announcement->audienceDepartment?->name,
            $announcement->for_clients ? 'also on the client board' : null,
            $announcement->observed_from !== null
                ? 'office closed '.$announcement->observed_from->format('D d M Y')
                    .($announcement->observed_to && ! $announcement->observed_to->isSameDay($announcement->observed_from)
                        ? ' to '.$announcement->observed_to->format('D d M Y')
                        : '')
                : null,
        ]));
    }

    /**
     * @return array<string, mixed>
     */
    protected function filters(Request $request): array
    {
        $validated = $request->validate([
            'q' => ['nullable', 'string', 'max:100'],
            'category' => ['nullable', Rule::in(array_keys(AnnouncementPresenter::categories()))],
        ]);

        $search = trim($validated['q'] ?? '');

        return [
            'search' => $search,
            'filterCategory' => $validated['category'] ?? null,
            'filtered' => $search !== '' || ($validated['category'] ?? null) !== null,
        ];
    }

    /**
     * @param  Collection<int, array<string, mixed>>  $announcements
     * @param  array<string, mixed>  $filters
     * @return Collection<int, array<string, mixed>>
     */
    protected function matching(Collection $announcements, array $filters): Collection
    {
        return $announcements
            ->when($filters['search'] !== '', fn (Collection $rows) => $rows->filter(
                fn (array $a) => str_contains(
                    mb_strtolower($a['title'].' '.$a['id'].' '.$a['body']),
                    mb_strtolower($filters['search'])
                )
            ))
            ->when($filters['filterCategory'], fn (Collection $rows) => $rows->where('category', $filters['filterCategory']))
            ->sortByDesc('published_at')
            ->values();
    }

    /**
     * @param  Collection<int, array<string, mixed>>  $rows
     * @return LengthAwarePaginator<int, array<string, mixed>>
     */
    protected function paginate(Collection $rows, Request $request): LengthAwarePaginator
    {
        $page = LengthAwarePaginator::resolveCurrentPage();

        return new LengthAwarePaginator(
            items: $rows->forPage($page, self::PER_PAGE)->values(),
            total: $rows->count(),
            perPage: self::PER_PAGE,
            currentPage: $page,
            options: ['path' => $request->url(), 'query' => $request->query()],
        );
    }
}
