<?php

namespace App\Http\Controllers;

use App\Support\Demo\DemoNotifications;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Validation\Rule;

/**
 * Notifications — the other half of Announcements, and deliberately separate.
 *
 * One page: `/notifications`, the full version of what the topbar bell shows.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * ADDRESSED TO ONE PERSON
 *
 * Decided 2026-08-28. A notification is generated by an event, belongs to one
 * reader, usually points at something they must do, and is cleared when read.
 * That is the opposite of an announcement in every respect, which is why they
 * are two surfaces sharing one feed component rather than one merged list.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHAT THE BACKEND OWES
 *
 * 1. SCOPING IS NOT OPTIONAL. `DemoNotifications::for()` takes the reader as a
 *    required argument and there is no `all()`, so fetching somebody else's
 *    queue is not something a forgotten `where` can cause. Keep that shape.
 *
 * 2. MARKING READ IS THE READER'S OWN. Nobody clears anybody else's, and
 *    nothing marks a row read on behalf of a person who has not seen it.
 *
 * 3. A LINK POINTS SOMEWHERE REAL. A notification for a page that does not
 *    exist is a promise the application cannot keep, and it fails at the moment
 *    somebody acts on it — see DemoNotifications::linkFor().
 * ─────────────────────────────────────────────────────────────────────────────
 */
class NotificationController extends Controller
{
    /**
     * GET /notifications
     */
    public function index(Request $request): Response
    {
        $tab = $request->validate([
            'tab' => ['nullable', Rule::in(['all', 'unread'])],
        ])['tab'] ?? 'all';

        $viewer = DemoNotifications::VIEWER;
        $mine = DemoNotifications::for($viewer);

        return response()->view('notifications.index', [
            'activeNav' => 'notifications',
            'notificationList' => $tab === 'unread' ? $mine->whereNull('read_at')->values() : $mine,
            'tab' => $tab,
            'tabCounts' => [
                'all' => $mine->count(),
                'unread' => $mine->whereNull('read_at')->count(),
            ],
        ]);
    }
}
