<?php

namespace App\Http\Controllers;

use App\Support\NotificationDirectory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Validation\Rule;

/**
 * Notifications — the other half of Announcements, and deliberately separate.
 *
 * One page: `/notifications`, the full version of what the topbar bell shows.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * ADDRESSED TO ONE PERSON
 *
 * Decided 2026-08-28. A notification is generated by an event, belongs to one
 * reader, usually points at something they must do, and is cleared when read.
 * That is the opposite of an announcement in every respect, which is why they
 * are two surfaces sharing one feed component rather than one merged list.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * THE THREE RULES, AND WHERE EACH ONE NOW LIVES
 *
 * 1. SCOPING IS NOT OPTIONAL. `NotificationDirectory` takes the reader as a
 *    required argument on every method and has no `all()`, so fetching somebody
 *    else's queue is not something a forgotten `where` can cause.
 *
 * 2. MARKING READ IS THE READER'S OWN. `read()` works on the signed-in
 *    account's rows and takes no id, so there is no parameter to tamper with —
 *    nobody clears anybody else's, and nothing marks a row read on behalf of a
 *    person who has not seen it.
 *
 * 3. A LINK POINTS SOMEWHERE REAL. Checked at render, from a stored route name
 *    — see Notification::link().
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * NO PERMISSION GATES ANYWHERE ON THIS PAGE
 *
 * Every other module's writes sit behind a §5 permission. This one has none,
 * and it is not a gap: the page shows the signed-in person their own queue and
 * the only write marks their own rows read. A permission would be a control
 * over whether somebody may read something addressed to them, which is not a
 * question the company has — and one nobody would ever be safe to revoke,
 * because it would silently stop leave decisions reaching people.
 *
 * NOT AUDITED, FOR THE SAME REASON
 *
 * §6 is for things somebody could later argue about. "Read your own
 * notifications" is not one, and at one entry per bell click it would bury the
 * ones that are.
 * ─────────────────────────────────────────────────────────────────────────────
 */
class NotificationController extends Controller
{
    /**
     * GET /notifications
     */
    public function index(Request $request): Response
    {
        $tab = $request->validate([
            'tab' => ['nullable', Rule::in(['all', 'unread'])],
        ])['tab'] ?? 'all';

        $reader = $request->user();

        $mine = NotificationDirectory::for($reader);
        $unread = $mine->whereNull('read_at')->values();

        return response()->view('notifications.index', [
            'activeNav' => 'notifications',
            'notificationList' => $tab === 'unread' ? $unread : $mine,
            'tab' => $tab,
            'tabCounts' => [
                'all' => $mine->count(),
                'unread' => $unread->count(),
            ],
        ]);
    }

    /**
     * POST /notifications/read — mark the reader's own unread rows read.
     *
     * Takes nothing. There is no `{notification}` to pass, because a route that
     * accepted one would need a check that it belonged to the person asking,
     * and the check that is never written is the one guarding the route nobody
     * thought was interesting.
     */
    public function read(Request $request): RedirectResponse
    {
        $moved = NotificationDirectory::markAllRead($request->user());

        return redirect()
            ->route('notifications.index')
            ->with('status', $moved === 0
                ? 'Nothing was unread.'
                : ($moved === 1 ? 'One notification marked as read.' : $moved.' notifications marked as read.'))
            ->with('status_tone', $moved === 0 ? 'info' : 'success');
    }
}
