<?php

namespace App\Support\Demo;

use Illuminate\Support\Carbon;
use Illuminate\Support\Collection;

/**
 * Sample notifications — the other half of Announcements.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * A NOTIFICATION IS ADDRESSED TO ONE PERSON
 *
 * Decided 2026-08-28. This is deliberately NOT the announcements board:
 *
 *   - it is generated by an event, not written by anyone;
 *   - it goes to one person, not to everyone;
 *   - it usually points at something that person has to do;
 *   - it is cleared when read.
 *
 * Task and ticket events are high-volume and nobody else's business. Put them
 * on the board and the day somebody posts "office closed Friday" it sits under
 * forty task assignments and people turn up.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * EVERY ROW BELONGS TO SOMEBODY
 *
 * `for()` takes the reader as a required argument, so there is no way to fetch
 * "the notifications" without saying whose — the same shape DemoTickets uses
 * for comment visibility, for the same reason: forgetting to scope should be a
 * syntax error rather than one person reading another's queue.
 * ─────────────────────────────────────────────────────────────────────────────
 */
class DemoNotifications
{
    /** The person the bell stands in for until authentication lands. */
    public const VIEWER = 'EMP002';

    public static function enabled(): bool
    {
        return app()->environment('local') && config('app.debug');
    }

    /**
     * `mins` is minutes ago. `read` marks it already seen.
     *
     * @return list<array<string, mixed>>
     */
    protected static function rows(): array
    {
        return [
            ['user' => 'EMP002', 'kind' => 'task', 'icon' => 'tasks', 'mins' => 12, 'read' => false,
             'title' => 'Rahul Mehta assigned you a task',
             'body' => 'Wire the checkout error states — due Friday.',
             'route' => 'tasks.index', 'params' => []],

            ['user' => 'EMP002', 'kind' => 'ticket', 'icon' => 'tickets', 'mins' => 55, 'read' => false,
             'title' => 'Ticket escalated to you',
             'body' => 'TKT-2026-148 — Request to add a new admin user.',
             'route' => 'tickets.show', 'params' => ['ticket' => 'TKT-2026-148']],

            ['user' => 'EMP002', 'kind' => 'meeting', 'icon' => 'meetings', 'mins' => 90, 'read' => false,
             'title' => 'Sprint planning starts soon',
             'body' => 'Today, and you have not replied to the invite.',
             'route' => 'meetings.show', 'params' => ['meeting' => 'MTG-2026-058']],

            ['user' => 'EMP002', 'kind' => 'leave', 'icon' => 'leave', 'mins' => 60 * 20, 'read' => true,
             'title' => 'Your leave was approved',
             'body' => 'Casual leave, 1 day.',
             'route' => 'leave.mine', 'params' => []],

            ['user' => 'EMP002', 'kind' => 'invoice', 'icon' => 'invoices', 'mins' => 60 * 30, 'read' => true,
             'title' => 'Payment received',
             'body' => 'Innovate Hub paid $2,000 against INV-2026-013.',
             'route' => 'invoices.show', 'params' => ['invoice' => 'INV-2026-013']],

            ['user' => 'EMP002', 'kind' => 'project', 'icon' => 'projects', 'mins' => 60 * 46, 'read' => true,
             'title' => 'Website Redesign is due in 5 days',
             'body' => 'Progress is at 75%.',
             'route' => 'projects.show', 'params' => ['project' => 'WD-2024-001']],

            // Somebody else's, so the scoping has something to exclude.
            ['user' => 'EMP004', 'kind' => 'task', 'icon' => 'tasks', 'mins' => 30, 'read' => false,
             'title' => 'Amit Verma assigned you a task',
             'body' => 'Review the payment gateway logs.',
             'route' => 'tasks.index', 'params' => []],
        ];
    }

    /**
     * One person's notifications, most recent first.
     *
     * The reader is a required argument. There is deliberately no `all()`.
     *
     * @return Collection<int, array<string, mixed>>
     */
    public static function for(string $employeeId): Collection
    {
        if (! self::enabled()) {
            return collect();
        }

        return collect(self::rows())
            ->where('user', $employeeId)
            ->map(function (array $row) {
                $at = Carbon::now()->subMinutes($row['mins']);

                return $row + [
                    'id' => 'NTF-'.$row['user'].'-'.$row['mins'],
                    'link' => self::linkFor($row),
                    'created_at' => $at->toDateTimeString(),
                    'read_at' => $row['read'] ? $at->copy()->addMinutes(5)->toDateTimeString() : null,
                    'when' => $at->diffForHumans(short: true),
                ];
            })
            ->sortByDesc('created_at')
            ->values();
    }

    /**
     * A route that exists, or nothing.
     *
     * A notification pointing at a page that has not been built is worse than
     * one with no link: it is a promise the application cannot keep, and it
     * fails at the moment somebody acts on it.
     *
     * @param  array<string, mixed>  $row
     */
    protected static function linkFor(array $row): ?string
    {
        if (! app('router')->has($row['route'])) {
            return null;
        }

        return route($row['route'], $row['params']);
    }

    /**
     * @return Collection<int, array<string, mixed>>
     */
    public static function unreadFor(string $employeeId): Collection
    {
        return self::for($employeeId)->whereNull('read_at')->values();
    }

    /**
     * What the bell shows: the newest few, not everything.
     *
     * A panel that lists two hundred rows is a page, and this one has to open
     * and be understood in a second.
     *
     * @return list<array<string, mixed>>
     */
    public static function bellFor(string $employeeId, int $limit = 6): array
    {
        return self::for($employeeId)->take($limit)->values()->all();
    }
}
